# Generated by Django 6.0 on 2025-12-15 10:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('loft', 'Loft'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('house', 'House'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('room', 'Private Room'), ('shared_room', 'Shared Room')], max_length=20, verbose_name='Property Type')),
                ('address', models.CharField(max_length=255, verbose_name='Full Address')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='House Number')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Germany', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal_code')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('area_sqm', models.IntegerField(blank=True, null=True)),
                ('has_wifi', models.BooleanField(default=True, help_text='Property has Wi-Fi internet access', verbose_name='Wi-Fi')),
                ('has_kitchen', models.BooleanField(default=True, help_text='Property has a kitchen or kitchenette', verbose_name='Kitchen')),
                ('has_tv', models.BooleanField(default=True, help_text='Property has television', verbose_name='TV')),
                ('has_ac', models.BooleanField(default=False, help_text='Property has air conditioning', verbose_name='Air Conditioning')),
                ('has_washer', models.BooleanField(default=False, help_text='Property has a washing machine', verbose_name='Washing Machine')),
                ('has_parking', models.BooleanField(default=False, help_text='Property has parking space available', verbose_name='Parking')),
                ('has_balcony', models.BooleanField(default=False, help_text='Property has a balcony or terrace', verbose_name='Balcony/Terrace')),
                ('has_pets_allowed', models.BooleanField(default=False, help_text='Pets are allowed in the property', verbose_name='Pets Allowed')),
                ('has_smoking_allowed', models.BooleanField(default=False, help_text='Smoking is allowed in the property', verbose_name='Smoking Allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_objects', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Real Estate Object',
                'verbose_name_plural': 'Real Estate Objects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(blank=True, help_text='Optional promotional text for special offers or discounts', max_length=200, verbose_name='Promo Title')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price Per Night')),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='EUR', max_length=3, verbose_name='Currency')),
                ('minimum_stay', models.IntegerField(default=1, help_text='Minimum number of nights required', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Stay')),
                ('check_in_time', models.TimeField(default='15:00', verbose_name='Check-in Time')),
                ('check_out_time', models.TimeField(default='11:00', verbose_name='Check-out Time')),
                ('cancellation_days_before', models.PositiveIntegerField(default=2, help_text='Guest can cancel up to this many days before check-in', verbose_name='Cancellation Days Before Check-in')),
                ('is_active', models.BooleanField(default=True, help_text='Show this listing in search results', verbose_name='Is Active')),
                ('is_approved', models.BooleanField(default=False, help_text='Listing has been approved by moderator', verbose_name='Is Approved')),
                ('moderation_notes', models.TextField(blank=True, help_text='Notes from moderator (visible only to staff)', verbose_name='Moderation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('real_estate_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.realestateobject', verbose_name='Real Estate Object')),
            ],
            options={
                'verbose_name': 'Real Estate Listing',
                'verbose_name_plural': 'Real Estate Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
