# Generated by Django 6.0 on 2025-12-15 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatelisting',
            name='cancellation_days_before',
            field=models.PositiveSmallIntegerField(default=2, help_text='Guest can cancel up to this many days before check-in (0-365)', validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Cancellation Days Before Check-in'),
        ),
        migrations.AlterField(
            model_name='realestatelisting',
            name='check_in_time',
            field=models.TimeField(default='15:00', max_length=5, verbose_name='Check-in Time'),
        ),
        migrations.AlterField(
            model_name='realestatelisting',
            name='check_out_time',
            field=models.TimeField(default='11:00', max_length=5, verbose_name='Check-out Time'),
        ),
        migrations.AlterField(
            model_name='realestatelisting',
            name='minimum_stay',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of nights required (1-365)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Minimum Stay'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='area_sqm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Area (m²)'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='max_guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='rooms',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
