# Generated by Django 6.0 on 2025-12-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_realestatelisting_cancellation_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatelisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this listing was viewed', verbose_name='View Count'),
        ),
    ]
