# Generated by Django 6.0 on 2025-12-18 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_realestatelisting_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('category', models.CharField(choices=[('essentials', 'Essentials'), ('comfort', 'Comfort'), ('outside', 'Outside'), ('rules', 'Rules')], default='essentials', max_length=20, verbose_name='Category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Rooms')),
                ('bathrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Bathrooms')),
                ('max_guests', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Max Guests')),
                ('area_sqm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Area (m²)')),
            ],
            options={
                'verbose_name': 'Property Stats',
                'verbose_name_plural': 'Property Stats',
            },
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='city',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='country',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='district',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_kitchen',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_pets_allowed',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_smoking_allowed',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_tv',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_washer',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='realestateobject',
            name='street',
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Germany', max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='House Number')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'unique_together': {('country', 'city', 'street', 'house_number')},
            },
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='stats',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_object', to='properties.propertystats', verbose_name='Property Stats'),
            preserve_default=False,
        ),
    ]
