# Generated by Django 6.0 on 2025-12-25 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_amenity_propertystats_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='address',
            name='is_normalized',
            field=models.BooleanField(default=False, help_text='Address has been processed by geocoder', verbose_name='Is Normalized'),
        ),
        migrations.AddField(
            model_name='realestateobject',
            name='address_raw',
            field=models.TextField(blank=True, help_text='Original address entered by host (before normalization)', verbose_name='Raw Address Input'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('comfort', 'Comfort'), ('outside', 'Outside'), ('luxury', 'Luxury'), ('accessibility', 'Accessibility'), ('rules', 'Rules')], default='essentials', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.address', verbose_name='Normalized Address'),
        ),
    ]
