# Generated by Django 6.0 on 2025-12-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique role identifier (e.g., 'host', 'guest', 'moderator')", max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='What this role allows users to do', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, verbose_name='About me')),
                ('satisfaction_total_score', models.FloatField(default=0.0, help_text='Sum of points for satisfaction (TOP=100, OK=50, POOR=0)', verbose_name='Satisfaction total score')),
                ('satisfaction_votes_count', models.IntegerField(default=0, help_text='Total number of satisfaction ratings received', verbose_name='Satisfaction votes count')),
                ('satisfaction_top_count', models.IntegerField(default=0, help_text='Number of TOP ratings for satisfaction', verbose_name='Satisfaction TOP count')),
                ('satisfaction_ok_count', models.IntegerField(default=0, help_text='Number of OK ratings for satisfaction', verbose_name='Satisfaction OK count')),
                ('satisfaction_poor_count', models.IntegerField(default=0, help_text='Number of POOR ratings for satisfaction', verbose_name='Satisfaction POOR count')),
                ('friendliness_total_score', models.FloatField(default=0.0, help_text='Sum of points for friendliness (TOP=100, OK=50, POOR=0)', verbose_name='Friendliness total score')),
                ('friendliness_votes_count', models.IntegerField(default=0, help_text='Total number of friendliness ratings received', verbose_name='Friendliness votes count')),
                ('friendliness_top_count', models.IntegerField(default=0, help_text='Number of TOP ratings for friendliness', verbose_name='Friendliness TOP count')),
                ('friendliness_ok_count', models.IntegerField(default=0, help_text='Number of OK ratings for friendliness', verbose_name='Friendliness OK count')),
                ('friendliness_poor_count', models.IntegerField(default=0, help_text='Number of POOR ratings for friendliness', verbose_name='Friendliness POOR count')),
                ('reliability_total_score', models.FloatField(default=0.0, help_text='Sum of points for reliability (TOP=100, OK=50, POOR=0)', verbose_name='Reliability total score')),
                ('reliability_votes_count', models.IntegerField(default=0, help_text='Total number of reliability ratings received', verbose_name='Reliability votes count')),
                ('reliability_top_count', models.IntegerField(default=0, help_text='Number of TOP ratings for reliability', verbose_name='Reliability TOP count')),
                ('reliability_ok_count', models.IntegerField(default=0, help_text='Number of OK ratings for reliability', verbose_name='Reliability OK count')),
                ('reliability_poor_count', models.IntegerField(default=0, help_text='Number of POOR ratings for reliability', verbose_name='Reliability POOR count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('roles', models.ManyToManyField(blank=True, related_name='profiles', to='users.role', verbose_name='Roles')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
