# Generated by Django 6.0 on 2025-12-15 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message="Phone number must start with '+' followed by 7 to 12 digits", regex='^\\+\\d{7,12}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="Unique role identifier (e.g., 'host', 'guest', 'moderator')", max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last name'),
        ),
    ]
