# Generated by Django 6.0 on 2026-01-04 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phone_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message="Phone number must start with '+' followed by 7 to 13 digits", regex='^\\+\\d{7,13}$')], verbose_name='Phone number'),
        ),
    ]
