# Generated by Django 6.0 on 2026-01-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ratings_given_count',
            field=models.IntegerField(default=0, help_text='Number of ratings given to other users', verbose_name='Ratings given count'),
        ),
    ]
