# Generated by Django 6.0 on 2026-01-04 20:29

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0005_alter_address_unique_together_address_is_normalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(default=datetime.date(2028, 1, 4), help_text='Last available date (max 2 years from today)', verbose_name='End Date'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__lte', datetime.date(2028, 1, 4))), name='end_date_within_max_limit'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__lte', datetime.date(2028, 1, 4))), name='booking_within_max_limit'),
        ),
    ]
