# Generated by Django 6.0 on 2025-12-15 22:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0002_alter_realestatelisting_cancellation_days_before_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Detailed review comment', max_length=1000, verbose_name='Comment')),
                ('is_approved', models.BooleanField(default=False, help_text='Review is hidden until moderator approves')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booking', models.OneToOneField(help_text='The booking this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='property_review', to='bookings.booking', verbose_name='Booking')),
                ('guest', models.ForeignKey(help_text='Guest who left the review', on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Guest')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.realestatelisting', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Property Review',
                'verbose_name_plural': 'Property Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'created_at'], name='reviews_pro_listing_9c4048_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_review_per_booking')],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('satisfaction', 'Satisfaction'), ('friendliness', 'Friendliness'), ('reliability', 'Reliability')], help_text='Rating category', max_length=20, verbose_name='Category')),
                ('rating', models.CharField(choices=[('TOP', 'TOP'), ('OK', 'OK'), ('POOR', 'POOR')], help_text='Rating value (TOP/OK/POOR)', max_length=10, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Optional explanation for the rating', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('booking', models.ForeignKey(help_text='Booking this rating is for', on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='bookings.booking', verbose_name='Booking')),
                ('rated_user', models.ForeignKey(help_text='User being rated', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Rated User')),
                ('rating_user', models.ForeignKey(help_text='User giving the rating', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Rating User')),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rated_user', 'category'], name='reviews_use_rated_u_7fb301_idx')],
                'constraints': [models.UniqueConstraint(fields=('rated_user', 'rating_user', 'category', 'booking'), name='unique_rating_per_category_booking')],
            },
        ),
    ]
