# Generated by Django 6.0 on 2026-01-05 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_availability_end_date_within_max_limit_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrating',
            name='unique_rating_per_category_booking',
        ),
        migrations.RemoveIndex(
            model_name='userrating',
            name='reviews_use_rated_u_7fb301_idx',
        ),
        migrations.AddField(
            model_name='userrating',
            name='friendliness',
            field=models.CharField(choices=[('TOP', 'TOP'), ('OK', 'OK'), ('POOR', 'POOR')], default='OK', help_text='Friendliness rating (TOP/OK/POOR)', max_length=10, verbose_name='Friendliness'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='reliability',
            field=models.CharField(choices=[('TOP', 'TOP'), ('OK', 'OK'), ('POOR', 'POOR')], default='OK', help_text='Reliability rating (TOP/OK/POOR)', max_length=10, verbose_name='Reliability'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='satisfaction',
            field=models.CharField(choices=[('TOP', 'TOP'), ('OK', 'OK'), ('POOR', 'POOR')], default='OK', help_text='Satisfaction rating (TOP/OK/POOR)', max_length=10, verbose_name='Satisfaction'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('booking', 'rating_user', 'rated_user'), name='unique_rating_per_booking_pair'),
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rating',
        ),
    ]
